### ISSUE TITLE
Tabs should close on middle click

### ISSUE THREAD

**Issue by Kommynct** [Cogitri/Tau#325]
I exclusively use middleclick to close tabs of things rather than the X, I find it's just better than having to be accurate, and nearly all programs do this.

How hard would it be to add it to gxi for someone who knows practically nothing about coding? I'd like to contribute if possible.

Also maybe add an option to toggle off the X's because i don't want to accidentally click one.

**Comment by Cogitri** [comment]
> I exclusively use middleclick to close tabs of things rather than the X, I find it's just better than having to be accurate, and nearly all programs do this.

Good idea, thanks for the idea!

> How hard would it be to add it to gxi for someone who knows practically nothing about coding? I'd like to contribute if possible.

Hm, I don't think that this is a good starter issue, due to event handling needing some knowledge with GTK. I'll open a PR for this in a bit, if you want to you can give it a look and asks questions for stuff you don't understand. If you want to you can also look at Tau's docs. Run `cargo doc --document-private-items --open` (or browse the sourcecode directly, everything behind `///` is docs)  and see if there's stuff you don't understand, Tau's docs really need to be upped.

> Also maybe add an option to toggle off the X's because i don't want to accidentally click one.

Hmmm...I feel like this doesn't fit well with the GNOME Human Interface Guidelines:

>  When considering adding options to your app, try to strike a balance of making your app more accessible without pushing design work onto your users.

**Comment by Cogitri** [comment]
Actually, building docs with `cargo doc` doesn't work due to https://github.com/rust-lang/rust/issues/61732 right now.
